# Generated by Django 4.2.30 on 2026-06-08 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المتدرب')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('height', models.FloatField(verbose_name='الطول (سم)')),
                ('current_weight', models.FloatField(verbose_name='الوزن الحالي (كغ)')),
                ('target_weight', models.FloatField(verbose_name='الوزن المستهدف (كغ)')),
                ('start_date', models.DateField(verbose_name='تاريخ بداية الاشتراك')),
                ('end_date', models.DateField(verbose_name='تاريخ نهاية الاشتراك')),
                ('coach_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات المدرب (سرية)')),
            ],
        ),
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='الوزن المسجل (كغ)')),
                ('date_recorded', models.DateField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.trainee', verbose_name='المتدرب')),
            ],
        ),
    ]
