# Generated by Django 4.2.30 on 2026-06-09 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainee',
            options={'verbose_name': 'متدرب', 'verbose_name_plural': 'المتدربون'},
        ),
        migrations.AlterModelOptions(
            name='weightrecord',
            options={'verbose_name': 'سجل وزن', 'verbose_name_plural': 'سجلات الأوزان'},
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='email',
        ),
        migrations.AddField(
            model_name='trainee',
            name='monthly_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='التكلفة شهرياً'),
        ),
        migrations.AddField(
            model_name='trainee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الجوال'),
        ),
        migrations.AddField(
            model_name='trainee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='حساب الدخول'),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='end_date',
            field=models.DateField(verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم الكامل'),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='start_date',
            field=models.DateField(verbose_name='تاريخ البدء بالتسجيل'),
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان اليوم (مثال: يوم الظهر والبايسبس)')),
                ('exercises_details', models.TextField(verbose_name='تفاصيل التمارين')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.trainee', verbose_name='المتدرب')),
            ],
            options={
                'verbose_name': 'برنامج تدريبي',
                'verbose_name_plural': 'البرامج التدريبية',
            },
        ),
        migrations.CreateModel(
            name='DietProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان اليوم (مثال: اليوم الأول)')),
                ('meals_details', models.TextField(verbose_name='تفاصيل الوجبات')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.trainee', verbose_name='المتدرب')),
            ],
            options={
                'verbose_name': 'برنامج غذائي',
                'verbose_name_plural': 'البرامج الغذائية',
            },
        ),
    ]
