# Generated by Django 4.2.30 on 2026-06-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_alter_trainee_options_alter_weightrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='trainees_images/'),
        ),
        migrations.AddField(
            model_name='trainee',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to='trainees_images/'),
        ),
        migrations.AddField(
            model_name='trainee',
            name='side_image',
            field=models.ImageField(blank=True, null=True, upload_to='trainees_images/'),
        ),
    ]
