# Generated by Django 4.2.30 on 2026-06-15 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0004_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='training_media/'),
        ),
    ]
