# Generated by Django 4.2.30 on 2026-06-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0005_trainingprogram_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietprogram',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='diet_media/'),
        ),
    ]
